import React,{useEffect,useState}from'react'
import{createRoot}from'react-dom/client'
import{ArrowDown,ArrowUpRight,Check,Menu,MoveDiagonal2,Plus,X}from'lucide-react'
import{BrowserRouter,useLocation}from'react-router-dom'
import{siteConfig,testimonials}from'./config/site'
import{supabase}from'./lib/supabase'
import Admin from'./pages/Admin'
import'./styles.css'

const Frame=({children,className=''})=><div className={'frame '+className}><div className="rail"/>{children}<div className="rail"/></div>
function Header(){const[open,setOpen]=useState(false);return <Frame className="nav-frame"><header><a className="brand" href="#home"><MoveDiagonal2/> PIXELD</a><nav className={open?'open':''}>{['Projects','Services','Pricing','Contact'].map(x=><a onClick={()=>setOpen(false)} key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><a className="nav-cta" href="#contact">Let’s Work Together</a><button className="menu" aria-label="Menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header></Frame>}
const Label=({children})=><div className="section-label"><i/>{children}</div>
function Hero(){return <><Frame><section className="hero" id="home"><div className="hero-image"><img src="/images/khalid-hero.png" alt="Khalid Alketbi, founder of PIXELD"/></div><h1>Hi, I’m Khalid Alketbi</h1><div className="roles">{siteConfig.hero.roles.map(x=><strong key={x}>{x}</strong>)}</div><p>{siteConfig.hero.subheadline}</p></section></Frame><Frame><Label>About Me</Label></Frame></>}
function About(){return <><Frame><section className="about" id="about"><div className="about-image"><img src="/images/khalid-about.png" alt="Portrait of Khalid Alketbi" loading="lazy"/><div className="orbit">PIXELD · DIGITAL EXPERIENCES · PIXELD ·</div></div><div className="about-copy"><span>I’m</span><h2>Khalid</h2><p>{siteConfig.about}</p><a href="#contact">Let’s Connect <ArrowUpRight/></a></div></section></Frame><Frame><div className="stats">{siteConfig.stats.map(s=><div key={s.label}><strong>{s.value}</strong><span>{s.label}</span></div>)}</div></Frame><Frame><div className="values"><span>Bold Vision</span><span>Visual Balance</span><span>Detail in Every Line</span><span>Create Without<br/>Boundaries</span></div></Frame></>}
function Projects(){const[projects,setProjects]=useState([]);useEffect(()=>{supabase?.from('projects').select('*,project_images(*)').eq('is_visible',true).order('sort_order').then(({data})=>setProjects(data||[]))},[]);return <><Frame><Label>Projects</Label></Frame><Frame><section className="projects" id="projects">{projects.length?<div className="project-grid">{projects.map(p=><article key={p.id}><a href={p.website_url||p.case_study_url||'#'} target={p.website_url||p.case_study_url?'_blank':undefined} rel="noreferrer"><div className="project-cover">{p.cover_image_url?<img src={p.cover_image_url} alt={`${p.title} project`} loading="lazy"/>:<span>{p.title}</span>}<div className="project-arrow"><ArrowUpRight/></div></div><div className="project-info"><div><h3>{p.title}</h3><p>{p.client_name||p.category}</p></div><span>{p.project_year}</span></div></a></article>)}</div>:<div className="projects-empty"><strong>Selected work coming soon.</strong><p>Real client projects will be published here.</p></div>}</section></Frame></>}
function Testimonials(){if(!testimonials.length)return null;return <><Frame><Label>Testimonial</Label></Frame><Frame><section className="testimonials">{testimonials.map(t=><article key={t.name}><p>“{t.quote}”</p><div>{t.avatar&&<img src={t.avatar} alt=""/>}<span><strong>{t.name}</strong>{t.role}</span></div></article>)}</section></Frame></>}
function Services(){return <><Frame><Label>What I Do</Label></Frame><Frame><section className="services" id="services">{siteConfig.services.map(([name,description],i)=><article key={name}><span>{String(i+1).padStart(2,'0')}</span><h3>{name}</h3><p>{description}</p><ArrowUpRight/></article>)}</section></Frame></>}
const faq=[['What kinds of projects does PIXELD take on?','Websites, online stores, dashboards, loyalty systems, UI/UX work, payment integrations, and custom digital experiences.'],['How does a project start?','We begin with a short conversation about your goals, scope, content, timeline, and the right technical approach.'],['Can you work with an existing brand?','Yes. I can work within an established identity or help define a clearer digital direction for the project.'],['Will the website work on mobile?','Yes. Responsive behavior and mobile optimization are part of every package.'],['Can I manage content after launch?','Yes. Where appropriate, I can provide a content or admin system suited to the way your business operates.'],['Do you handle launch and integrations?','Yes. I can support deployment, payment integration, analytics, domains, and the final launch process.']]
function FAQs(){const[open,setOpen]=useState(0);return <><Frame><Label>FAQs</Label></Frame><Frame><section className="faq"><div className="faq-intro"><span>FAQs</span><h2>Everything you<br/>need to know</h2><p>Some of the most frequent questions I receive. If you need more details, feel free to contact me directly.</p></div><div className="faq-list">{faq.map(([q,a],i)=><article className={open===i?'active':''} key={q}><button onClick={()=>setOpen(open===i?-1:i)}><span>{i+1}.</span><strong>{q}</strong>{open===i?<X/>:<Plus/>}</button><p>{a}</p></article>)}</div></section></Frame></>}
function Pricing(){return <><Frame><Label>Pricing</Label></Frame><Frame><section className="pricing" id="pricing"><div className="pricing-intro"><h2>Clear plans for<br/>every project</h2><p>No surprises and no subscriptions — just focused starting packages for your next digital experience.</p></div><div className="price-grid">{siteConfig.pricing.map((p,i)=><article className={i===1?'dark':''} key={p.name}><div className="price-top"><span>{p.name}</span>{i===1&&<small>Popular</small>}</div><strong>{p.price}</strong><p>A considered starting point, tailored after we confirm your project scope.</p><b>What’s Included</b><ul>{p.features.map(f=><li key={f}><Check/>{f}</li>)}</ul><a href="#contact">Choose Plan <ArrowUpRight/></a></article>)}</div></section></Frame></>}
function Contact(){const[state,setState]=useState('idle');async function submit(e){e.preventDefault();setState('sending');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});if(!r.ok)throw 0;setState('success');e.currentTarget.reset()}catch{setState('error')}}return <><Frame><Label>Contact</Label></Frame><Frame><section className="contact" id="contact"><div><span>Have something in mind?</span><h2>Let’s work<br/>together.</h2><p>Tell me about the project, the business, and what you want the experience to achieve.</p></div><form onSubmit={submit}><label>Name<input required name="name" maxLength="80"/></label><label>Email<input required type="email" name="email" maxLength="120"/></label><div><label>Phone <small>Optional</small><input name="phone" maxLength="30"/></label><label>Business Name <small>Optional</small><input name="businessName" maxLength="100"/></label></div><label>Message<textarea required name="message" minLength="10" maxLength="3000" rows="4"/></label><input className="hp" name="website" tabIndex="-1" autoComplete="off"/><button disabled={state==='sending'}>{state==='sending'?'SENDING…':'SEND'} <ArrowUpRight/></button><p className={'status '+state}>{state==='success'?'Your message has been sent.':state==='error'?'Unable to send. Please try again.':''}</p></form></section></Frame></>}
function Footer(){return <Frame><footer><div><a className="brand" href="#home"><MoveDiagonal2/> PIXELD</a><p>Modern websites and digital experiences built with intention.</p></div><div><b>Info</b>{['Projects','Services','Pricing','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</div><div><b>Social</b>{siteConfig.social.instagram&&<a href={siteConfig.social.instagram}>Instagram</a>}{siteConfig.social.tiktok&&<a href={siteConfig.social.tiktok}>TikTok</a>}<span>{!siteConfig.social.instagram&&!siteConfig.social.tiktok?'Links coming soon':''}</span></div><small>© {new Date().getFullYear()} PIXELD. All rights reserved.</small></footer></Frame>}
function Home(){useEffect(()=>{const items=document.querySelectorAll('main section,.section-label');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');io.unobserve(e.target)}}),{threshold:.08});items.forEach(el=>io.observe(el));return()=>io.disconnect()},[]);return <><Header/><main><Hero/><About/><Projects/><Testimonials/><Services/><FAQs/><Pricing/><Contact/></main><Footer/><a className="to-top" href="#home"><ArrowDown/></a></>}
function Route(){return useLocation().pathname.startsWith('/admin')?<Admin/>:<Home/>}createRoot(document.getElementById('root')).render(<BrowserRouter><Route/></BrowserRouter>)
